### ISSUE TITLE
Images Position?

### ISSUE THREAD

**Issue by thurdev** [victorbnl/discord-pfp-banner-generator#3]
After generating the images
Base:
![wallpaper-oxm2y7-824103-Preview](https://user-images.githubusercontent.com/34294813/169787558-8d0299b0-00f1-4a9b-bd28-054cf7c9c622.jpg)

Generated files:

- banner
![banner](https://user-images.githubusercontent.com/34294813/169787607-379f3683-2a77-4d75-8f77-7e3524d530ce.png)
- pfp
![profile-picture](https://user-images.githubusercontent.com/34294813/169787662-432e6d8c-33fe-4736-9867-e0522dffd340.png)

Which position should I use now?
![image](https://user-images.githubusercontent.com/34294813/169787782-ba2b9f1f-2e28-45e9-a36d-605f50e0b945.png)

Not looking right
![image](https://user-images.githubusercontent.com/34294813/169787843-a6983f06-183d-450f-a239-1d8534590efd.png)

**Comment by victorbnl** [comment]
When setting the banner, did you use the generated banner, and not the original image? The banner should already be the perfect size to fit in

**Comment by thurdev** [comment]
Yes sir.

**Comment by thurdev** [comment]
Check it with the base image that i sent.

**Comment by victorbnl** [comment]
I did check it, and I can indeed reproduce it, I need to find time to figure out what the problem is

**Comment by lxnnydev** [comment]
@victorbnl Late reply, but im pretty sure this is on discords ends and not yours 👍

**Comment by victorbnl** [comment]
I had forgotten this issue! I really need to look into it. Yes it’s about Discord, but if they changed something in their interface, which is probably what they did, I still need to update the project accordingly.

**Comment by victorbnl** [comment]
I think this project can’t work anymore because banners are not the same format anymore when looking at the pop-up profile summary or the profile view.

![image](https://github.com/victorbnl/discord-pfp-banner-generator/assets/39555268/298a1fc1-7629-43dc-aba9-981202a86f24)

![image](https://github.com/victorbnl/discord-pfp-banner-generator/assets/39555268/7f54d7b2-1734-491d-80fa-228d186e00f4)

Not to mention that it, as far as I know, never worked on mobile devices anyway.

Therefore, I think I will discontinue the project.
